development:
  adapter: postgis
  database: sharknado_development
  encoding: utf8
  postgis_extension: postgis
  schema_search_path: '"$user", public, postgis'

test:
  adapter: postgis
  database: sharknado_test
  encoding: utf8
  postgis_extension: postgis
  schema_search_path: '"$user", public, postgis'